In [ ]:
print("hello sumit")
print("this is amazing")
# comments are completely ignored by the python

hello sumit
this is amazing


In [ ]:
pip install numpy


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# NUMPY array can hold only one datatype at a time.
arr = np.array([1,2,3,4,5.5])
print(arr)
print(type(arr))
print(arr.dtype)

[1.  2.  3.  4.  5.5]
<class 'numpy.ndarray'>
float64


In [ ]:
# FEW FUNCTIONALITIES OF NUMPY.
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#lets try decimal value gaps.
arr = np.arange(0,10,1.5)#start = 0,end = 10,step =1.5
print(arr)

[0.  1.5 3.  4.5 6.  7.5 9. ]


In [ ]:
# MATRIX
arr = np.arange(12).reshape(3,4)
print(arr)
print(arr.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
# LETS TRY ZEROS AND ONES IN NUMPY.
#ZEROS
arr = np.zeros(shape=(4,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# ONES
arr = np.ones(shape=(4,4))
print(arr)
#THATS IT NUMPY CAN ONLY DO THIS WITH ZEROS AND ONES.

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr = np.full((4,3),10)
print(arr)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
#ARTHEMATIC OPERATIONS IN NUMPY.
arr = np.array([1,2,3,4,5])
print(arr)

print(arr+2)
print(arr-2)
print(arr*2)
print(arr/2)

[1 2 3 4 5]
[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [ ]:
# MEAN
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(np.mean(arr))
print(np.median(arr))

[1 2 3 4 5 6 7]
4.0
4.0


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(arr>3)#IT WILL SHOW BOOLEAN .
print(arr[arr>3])# IT SHOWS NUMBERS GREATER THAN 3 ONLY.


[1 2 3 4 5 6 7]
[False False False  True  True  True  True]
[4 5 6 7]


In [ ]:
import numpy as np
#LETS TRY ARETHEMATIC OPERATIONS ON TWO ARRAYS SIMULTANEOUSLY.
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([10,20,30,40,50,60])
print(arr1)
print(arr2)
#ADDING

print(arr1+arr2)

#SUBTRACTING.

print(arr1-arr2)

# MULTIPLICATION

print(arr1*arr2)

# DIVISION

print(arr1/arr2)

#IT THROWS ERROR WHEN THE DIMENSIONS ARE DIFFERENT.

[1 2 3 4 5 6]
[10 20 30 40 50 60]
[11 22 33 44 55 66]
[ -9 -18 -27 -36 -45 -54]
[ 10  40  90 160 250 360]
[0.1 0.1 0.1 0.1 0.1 0.1]


In [ ]:
# MAKING SAME DIMENSIONS WITHOUT KNOWING ORIGINAL ONE.
arr = np.arange(12).reshape(3,4)
print(arr)

print(np.mean(arr))
print(np.mean(arr,axis=0)) # axis tells us which way it is going to take the mean (AT ROW LEVEL)
print(np.mean(arr,axis=1)) #AT COLOUMN LEVEL.
print(arr.ndim) #IT WILL SHOW THE DIMENSIONS/SHAPE OF TUPPLE.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]


In [ ]:
# LETS TALK ABOUT PANDAS

!pip install PANDAS

In [ ]:
import pandas as pd
import numpy as np

# LETS CREATE A PANDA SERIES

s1 = pd.Series([1,2,3,4,5])
s1



0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# LETS TRY CREATING A DATA BASE IN PANDAS

data ={'city': ['NEWYORK','DEHRADUN','GURGAON'],
       'population':[10000,20000,50000]}

df = pd.DataFrame(data)
df

city  population
0   NEWYORK       10000
1  DEHRADUN       20000
2   GURGAON       50000

In [ ]:
csv_url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

df = pd.read_csv(csv_url)
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [ ]:
df.tail(2)

PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
889          890         1       1  Behr, Mr. Karl Howell  male  26.0      0   
890          891         0       3    Dooley, Mr. Patrick  male  32.0      0   

     Parch  Ticket   Fare Cabin Embarked  
889      0  111369  30.00  C148        C  
890      0  370376   7.75   NaN        Q

In [ ]:
df.info() # THIS FUNCTION WILL SHOW ALL THE IFNORMATION .

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
import pandas as pd
data = {'name':['sumit','neel','baharat'],
        'age': ['25','28','30'],
        'education':['graduate','masters','phd'],
        'gender': ['m','m','m']
}
customer = pd.DataFrame(data)
customer

name age education gender
0    sumit  25  graduate      m
1     neel  28   masters      m
2  baharat  30       phd      m

In [ ]:
customer['name'] # FOR SINGLE COLOUMN


name            sumit
age                25
education    graduate
gender              m
Name: a, dtype: object

In [ ]:
#WE CAN UPDATE INDEX WITH

customer.index = ['a','b','c']
customer


name age education gender
a    sumit  25  graduate      m
b     neel  28   masters      m
c  baharat  30       phd      m

In [ ]:
#SIMILARLY WE CAN LOCATE A SINGLE ROW using index we created.

customer.loc['a']

name            sumit
age                25
education    graduate
gender              m
Name: a, dtype: object

In [ ]:
customer.iloc[1] # USING PYTHON INDEX >> 0,1,2.....

name            neel
age               28
education    masters
gender             m
Name: b, dtype: object

In [ ]:
customer

name age education gender
a    sumit  25  graduate      m
b     neel  28   masters      m
c  baharat  30       phd      m

In [ ]:
# WE CAN SET INDEX TO NAME ALSO.
customer.set_index('name')

age education gender
name                        
sumit    25  graduate      m
neel     28   masters      m
baharat  30       phd      m

In [ ]:
# FILTERING
customer.name == 'sumit'

a     True
b    False
c    False
Name: name, dtype: bool

In [ ]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
#SORTING VALUES BASED ON AGE.

df.sort_values('Age')

PassengerId  Survived  Pclass                                      Name  \
803          804         1       3           Thomas, Master. Assad Alexander   
755          756         1       2                 Hamalainen, Master. Viljo   
644          645         1       3                    Baclini, Miss. Eugenie   
469          470         1       3             Baclini, Miss. Helene Barbara   
78            79         1       2             Caldwell, Master. Alden Gates   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
803    male  0.42      0      1        2625   8.5167   NaN        C  
755    male  0.67      1      1      250649  14.5000   NaN        S  
644  female  0.75      2      1        2666  19.2583   NaN        C  
469  female  0.75      2      1        2666  19.2583   NaN        C  
78     male  0.83      0      2      248738  29.0000   NaN        S  
..      ...   ...    ...    ...         ...      ...   ...      ...  
859    male   NaN      0      0        2629   7.2292   NaN        C  
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male   NaN      0      0      345777   9.5000   NaN        S  
878    male   NaN      0      0      349217   7.8958   NaN        S  
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S  

[891 rows x 12 columns]

In [ ]:
df.sort_values('Age', ascending=False)

PassengerId  Survived  Pclass                                      Name  \
630          631         1       1      Barkworth, Mr. Algernon Henry Wilson   
851          852         0       3                       Svensson, Mr. Johan   
493          494         0       1                   Artagaveytia, Mr. Ramon   
96            97         0       1                 Goldschmidt, Mr. George B   
116          117         0       3                      Connors, Mr. Patrick   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
630    male  80.0      0      0       27042  30.0000   A23        S  
851    male  74.0      0      0      347060   7.7750   NaN        S  
493    male  71.0      0      0    PC 17609  49.5042   NaN        C  
96     male  71.0      0      0    PC 17754  34.6542    A5        C  
116    male  70.5      0      0      370369   7.7500   NaN        Q  
..      ...   ...    ...    ...         ...      ...   ...      ...  
859    male   NaN      0      0        2629   7.2292   NaN        C  
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male   NaN      0      0      345777   9.5000   NaN        S  
878    male   NaN      0      0      349217   7.8958   NaN        S  
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S  

[891 rows x 12 columns]

In [ ]:
#LETS CHECK WHERE DATA IS MISSING.
df['Age'].isna()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [ ]:
# GROUPBY.
df.groupby('Pclass').agg({'Fare':'mean','Age':'max','Survived':'mean'})

Fare   Age  Survived
Pclass                           
1       84.154687  80.0  0.629630
2       20.662183  70.0  0.472826
3       13.675550  74.0  0.242363

In [ ]:
# APPLYING FUNCTIONS.
def canVote(Age):
  if Age>18:
      return True
  else:
      return False
df['eligible2vote'] = df['Age'].apply(canVote)
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  eligible2vote  
0        0         A/5 21171   7.2500   NaN        S           True  
1        0          PC 17599  71.2833   C85        C           True  
2        0  STON/O2. 3101282   7.9250   NaN        S           True  
3        0            113803  53.1000  C123        S           True  
4        0            373450   8.0500   NaN        S           True  
..     ...               ...      ...   ...      ...            ...  
886      0            211536  13.0000   NaN        S           True  
887      0            112053  30.0000   B42        S           True  
888      2        W./C. 6607  23.4500   NaN        S          False  
889      0            111369  30.0000  C148        C           True  
890      0            370376   7.7500   NaN        Q           True  

[891 rows x 13 columns]

In [ ]:
# LETS TRY MERGING.
product_data = {
    'product_id': ['p1','p2','p3','p4'],
    'product_name':['product A','product B','product C','product D']
}
product_df = pd.DataFrame(product_data)
product_df

product_id product_name
0         p1    product A
1         p2    product B
2         p3    product C
3         p4    product D

In [ ]:
review_data = {
    'product_id': ['p1','p2','p3'],
    'review_score': [4.5, 3.8, 4.0],
    'review_comment': ['Great product','Need improvment','Satisfied']
}
review_df = pd.DataFrame(review_data)
review_df



product_id  review_score   review_comment
0         p1           4.5    Great product
1         p2           3.8  Need improvment
2         p3           4.0        Satisfied

In [ ]:
pd.merge(product_df,review_df,on='product_id',how='inner')

product_id product_name  review_score   review_comment
0         p1    product A           4.5    Great product
1         p2    product B           3.8  Need improvment
2         p3    product C           4.0        Satisfied

In [ ]:
product_df.merge(review_df,on='product_id',how='inner')

product_id product_name  review_score   review_comment
0         p1    product A           4.5    Great product
1         p2    product B           3.8  Need improvment
2         p3    product C           4.0        Satisfied

In [ ]:
pd.merge(product_df,review_df,on='product_id',how='left')

product_id product_name  review_score   review_comment
0         p1    product A           4.5    Great product
1         p2    product B           3.8  Need improvment
2         p3    product C           4.0        Satisfied
3         p4    product D           NaN              NaN

In [ ]:
pd.merge(product_df,review_df,on='product_id',how='right')

product_id product_name  review_score   review_comment
0         p1    product A           4.5    Great product
1         p2    product B           3.8  Need improvment
2         p3    product C           4.0        Satisfied